{{- if not .Values.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{ include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: {{ toYaml .Values.config | nindent 2 }}
{{- end }}
