image:
  name: quay.io/yeebase/mysql-client
  tag: gcloud-sdk
  pullPolicy: Always

# Specify which type of job should be created
tasks:
  backup:
    cron: false
    manual: false
  restore:
    cron: false
    manual: false

schedule: "0 3 * * *"

# Required: Specify your GCS Service Account Key and the Bucket where the Backup should be uploaded
gcs:
  serviceAccountKey: ""
  bucket:
    name: ""
    # the following line prefixes the backups with the defined directory. it must be blank or end with a /
    path: ""

# Required: Credentials of the database to backup
database:
  host: mariadb
  user: admin
  pass: dummy
  name: "--all-databases"
  charset: utf8

# Required: Name of the backupfile to be created
filename: ""

resources:
  # limits:
    # cpu: 100m
    # memory: 128Mi
  # requests:
    # cpu: 10m
    # memory: 16Mi

# Specify if any sanitize queries should be run
sanitize:
  enabled: false
  sql: []
