nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}

type: ClusterIP

# Both addresses and ports are required to install a service with the
# corresponding endpoint.
addresses: []
  # - ip: 10.92.96.3
ports: []
  # - port: 3306
  #   name: mysql
  #   ingress:
  #     hosts:
  #       - host: localhost
  #         paths:
  #           - '/'

# If type is ExternalName, externalName must be set
externalName: ""
