apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{ include "ssh.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 | trim }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ssh
      port: 22
  selector:
    {{ include "ssh.selector" . | indent 4 | trim }}
